version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: htxpt_fe_size
    volumes:
      - .:/usr/apps/htxpt_fe_size
    ports:
      - 3101:3101
    command: npm run dev
    environment:
      NODE_ENV: development
